### ISSUE TITLE
你好，请问数据文件可以在哪里下载到呢？

### ISSUE THREAD

**Issue by linauc** [llhthinker/BDCI2017-MingLue#2]

**Comment by llhthinker** [comment]
数据文件是属于比赛主办方所有，主办方规定：

> 所有赛题数据仅限数据下载本人于BDCI 2017大赛期间研究赛题使用，若未获得大赛组委会书面同意，不可另做他用或转交他人使用。

因此，建议直接联系主办方，联系方式可在[比赛官网](http://www.datafountain.cn/#/competitions/277/intro)找到。
