### ISSUE TITLE
请问Micro-Averaged-F1， Macro-Averaged-F1怎么分析

### ISSUE THREAD

**Issue by alyato** [llhthinker/BDCI2017-MingLue#4]
hi 
对于多分类，这两个概念不是很懂。

> 宏平均F1平等对待每一个类别，所以它的值主要受到稀有类别的影响，而微平均F1平等考虑文档集中的每一个文档，所以它的值受到常见类别的影响比较大。

假如数据是不平衡的。
如果Micro-Averaged-F1=0.94，Macro-Averaged-F1=0.96，

可不可以理解：因为数据不平衡，导致Macro-Averaged-F1的值较大？
谢谢。

**Comment by llhthinker** [comment]
微平均F1和宏平均F1都是针对类分布不均匀的数据。
简单来说，假设某一类的F1值很高，并且属于这类的数据个数占全体数据较大的比重，而另一类F1值很低，但是属于该类的数据个数较少，这样微平均F1往往大于宏平均F1。相反的，如果某一类的F1值很高，但是属于这类的数据个数较少，而F1值很低的那一类的数据个数较多，此时微平均F1将小于宏平均F1。
你可以根据这两个指标的具体计算公式再理解理解。
